
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ActionConfig : Luban.BeanBase
    {
        public ActionConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            ActionType = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); Param = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Param.Add(_e0);}}

            EndInit();
        }

        public static ActionConfig DeserializeActionConfig(ByteBuf _buf)
        {
            return new ActionConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 技能行为类型
        /// </summary>
        public readonly int ActionType;
        /// <summary>
        /// 参数
        /// </summary>
        public readonly System.Collections.Generic.List<string> Param;
    
        public const int __ID__ = 1209614648;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ActionType:" + ActionType + ","
            + "Param:" + Luban.StringUtil.CollectionToString(Param) + ","
            + "}";
        }

        partial void EndRef();
    }

}

