
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class BulletConfig : Luban.BeanBase
    {
        public BulletConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Shape = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); ShapeParam = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ShapeParam.Add(_e0);}}
            TotalTime = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); AwakeAction = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AwakeAction.Add(_e0);}}
            Interval = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); TickCastId = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TickCastId.Add(_e0);}}
            {int n0 = _buf.ReadSize(); TickAction = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TickAction.Add(_e0);}}
            {int n0 = _buf.ReadSize(); DestroyAction = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); DestroyAction.Add(_e0);}}
            TargetNum = _buf.ReadInt();
            TickLimit = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); Tick1 = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Tick1.Add(_e0);}}
            {int n0 = _buf.ReadSize(); Tick2 = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Tick2.Add(_e0);}}

            EndInit();
        }

        public static BulletConfig DeserializeBulletConfig(ByteBuf _buf)
        {
            return new BulletConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 形状
        /// </summary>
        public readonly int Shape;
        /// <summary>
        /// 形状参数
        /// </summary>
        public readonly System.Collections.Generic.List<string> ShapeParam;
        /// <summary>
        /// 持续时间
        /// </summary>
        public readonly int TotalTime;
        /// <summary>
        /// 创建时触发
        /// </summary>
        public readonly System.Collections.Generic.List<int> AwakeAction;
        /// <summary>
        /// 结算间隔
        /// </summary>
        public readonly int Interval;
        /// <summary>
        /// 结算技能编号
        /// </summary>
        public readonly System.Collections.Generic.List<int> TickCastId;
        /// <summary>
        /// 结算行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> TickAction;
        /// <summary>
        /// 销毁前触发
        /// </summary>
        public readonly System.Collections.Generic.List<int> DestroyAction;
        /// <summary>
        /// 目标个数
        /// </summary>
        public readonly int TargetNum;
        /// <summary>
        /// 结算次数限制
        /// </summary>
        public readonly int TickLimit;
        /// <summary>
        /// 1档（0.5s）
        /// </summary>
        public readonly System.Collections.Generic.List<int> Tick1;
        /// <summary>
        /// 1档（1s）
        /// </summary>
        public readonly System.Collections.Generic.List<int> Tick2;
    
        public const int __ID__ = 284876548;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Shape:" + Shape + ","
            + "ShapeParam:" + Luban.StringUtil.CollectionToString(ShapeParam) + ","
            + "TotalTime:" + TotalTime + ","
            + "AwakeAction:" + Luban.StringUtil.CollectionToString(AwakeAction) + ","
            + "Interval:" + Interval + ","
            + "TickCastId:" + Luban.StringUtil.CollectionToString(TickCastId) + ","
            + "TickAction:" + Luban.StringUtil.CollectionToString(TickAction) + ","
            + "DestroyAction:" + Luban.StringUtil.CollectionToString(DestroyAction) + ","
            + "TargetNum:" + TargetNum + ","
            + "TickLimit:" + TickLimit + ","
            + "Tick1:" + Luban.StringUtil.CollectionToString(Tick1) + ","
            + "Tick2:" + Luban.StringUtil.CollectionToString(Tick2) + ","
            + "}";
        }

        partial void EndRef();
    }

}

