
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class CastConfig : Luban.BeanBase
    {
        public CastConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            CastType = (CastType)_buf.ReadInt();
            {int n0 = _buf.ReadSize(); NumericTypeValue = new System.Collections.Generic.Dictionary<ENumericType, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { ENumericType _k0;  _k0 = (ENumericType)_buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     NumericTypeValue.Add(_k0, _v0);}}
            {int n0 = _buf.ReadSize(); SelfAction = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SelfAction.Add(_e0);}}
            {int n0 = _buf.ReadSize(); SelfActionParam = new System.Collections.Generic.List<long>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { long _e0;  _e0 = _buf.ReadLong(); SelfActionParam.Add(_e0);}}
            {int n0 = _buf.ReadSize(); HitAction = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); HitAction.Add(_e0);}}
            {int n0 = _buf.ReadSize(); HitActionParam = new System.Collections.Generic.List<long>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { long _e0;  _e0 = _buf.ReadLong(); HitActionParam.Add(_e0);}}
            ResName = _buf.ReadString();
            {int n0 = _buf.ReadSize(); InitCastPosL = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); InitCastPosL.Add(_e0);}}
            {int n0 = _buf.ReadSize(); InitCastPosR = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); InitCastPosR.Add(_e0);}}
            {int n0 = _buf.ReadSize(); InitCastScale = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); InitCastScale.Add(_e0);}}

            EndInit();
        }

        public static CastConfig DeserializeCastConfig(ByteBuf _buf)
        {
            return new CastConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 技能类型
        /// </summary>
        public readonly CastType CastType;
        /// <summary>
        /// 数值
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<ENumericType, long> NumericTypeValue;
        /// <summary>
        /// 自身行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> SelfAction;
        /// <summary>
        /// 自身行为参数
        /// </summary>
        public readonly System.Collections.Generic.List<long> SelfActionParam;
        /// <summary>
        /// 命中行为
        /// </summary>
        public readonly System.Collections.Generic.List<int> HitAction;
        /// <summary>
        /// 命中行为参数
        /// </summary>
        public readonly System.Collections.Generic.List<long> HitActionParam;
        /// <summary>
        /// 资源名称
        /// </summary>
        public readonly string ResName;
        /// <summary>
        /// 初始位置
        /// </summary>
        public readonly System.Collections.Generic.List<float> InitCastPosL;
        /// <summary>
        /// 初始位置
        /// </summary>
        public readonly System.Collections.Generic.List<float> InitCastPosR;
        /// <summary>
        /// 初始缩放
        /// </summary>
        public readonly System.Collections.Generic.List<float> InitCastScale;
    
        public const int __ID__ = 944053121;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "CastType:" + CastType + ","
            + "NumericTypeValue:" + Luban.StringUtil.CollectionToString(NumericTypeValue) + ","
            + "SelfAction:" + Luban.StringUtil.CollectionToString(SelfAction) + ","
            + "SelfActionParam:" + Luban.StringUtil.CollectionToString(SelfActionParam) + ","
            + "HitAction:" + Luban.StringUtil.CollectionToString(HitAction) + ","
            + "HitActionParam:" + Luban.StringUtil.CollectionToString(HitActionParam) + ","
            + "ResName:" + ResName + ","
            + "InitCastPosL:" + Luban.StringUtil.CollectionToString(InitCastPosL) + ","
            + "InitCastPosR:" + Luban.StringUtil.CollectionToString(InitCastPosR) + ","
            + "InitCastScale:" + Luban.StringUtil.CollectionToString(InitCastScale) + ","
            + "}";
        }

        partial void EndRef();
    }

}

