
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class CastConfigCategory : Singleton<CastConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, CastConfig> _dataMap;
        private readonly List<CastConfig> _dataList;
        
        public CastConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, CastConfig>();
            _dataList = new List<CastConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                CastConfig _v;
                _v = global::ET.CastConfig.DeserializeCastConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, CastConfig> GetAll() => _dataMap;
        public Dictionary<int, CastConfig> DataMap => _dataMap;
        public List<CastConfig> DataList => _dataList;

        public CastConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public CastConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

