
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class CastConfig : Luban.BeanBase
    {
        public CastConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            TotalTime = _buf.ReadInt();
            SelectType = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); SelectParam = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); SelectParam.Add(_e0);}}

            EndInit();
        }

        public static CastConfig DeserializeCastConfig(ByteBuf _buf)
        {
            return new CastConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 总时长
        /// </summary>
        public readonly int TotalTime;
        /// <summary>
        /// 目标选择方式
        /// </summary>
        public readonly int SelectType;
        /// <summary>
        /// 目标选择参数
        /// </summary>
        public readonly System.Collections.Generic.List<string> SelectParam;
    
        public const int __ID__ = 944053121;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TotalTime:" + TotalTime + ","
            + "SelectType:" + SelectType + ","
            + "SelectParam:" + Luban.StringUtil.CollectionToString(SelectParam) + ","
            + "}";
        }

        partial void EndRef();
    }

}

