
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class InitCastData : Luban.BeanBase
    {
        public InitCastData(ByteBuf _buf) 
        {
            InitCastId = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); InitCastPos = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); InitCastPos.Add(_e0);}}
            {int n0 = _buf.ReadSize(); InitCastScale = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); InitCastScale.Add(_e0);}}

            EndInit();
        }

        public static InitCastData DeserializeInitCastData(ByteBuf _buf)
        {
            return new InitCastData(_buf);
        }

        public readonly int InitCastId;
        public readonly System.Collections.Generic.List<float> InitCastPos;
        public readonly System.Collections.Generic.List<float> InitCastScale;
    
        public const int __ID__ = -1829096231;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "InitCastId:" + InitCastId + ","
            + "InitCastPos:" + Luban.StringUtil.CollectionToString(InitCastPos) + ","
            + "InitCastScale:" + Luban.StringUtil.CollectionToString(InitCastScale) + ","
            + "}";
        }

        partial void EndRef();
    }

}

