
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class ParticleEffectConfigCategory : Singleton<ParticleEffectConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, ParticleEffectConfig> _dataMap;
        private readonly List<ParticleEffectConfig> _dataList;
        
        public ParticleEffectConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ParticleEffectConfig>();
            _dataList = new List<ParticleEffectConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                ParticleEffectConfig _v;
                _v = global::ET.ParticleEffectConfig.DeserializeParticleEffectConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, ParticleEffectConfig> GetAll() => _dataMap;
        public Dictionary<int, ParticleEffectConfig> DataMap => _dataMap;
        public List<ParticleEffectConfig> DataList => _dataList;

        public ParticleEffectConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public ParticleEffectConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

