
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    public partial struct CreateMonsterData
    {
        public CreateMonsterData(ByteBuf _buf) 
        {

            PostInit();
        }

        public static CreateMonsterData DeserializeCreateMonsterData(ByteBuf _buf)
        {
            return new CreateMonsterData(_buf);
        }

    

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
        partial void EndRef();
    }

}

