
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum TileType
    {
        /// <summary>
        /// 地块
        /// </summary>
        Tile = 0,
        /// <summary>
        /// 规则地块
        /// </summary>
        RuleTile = 1,
        /// <summary>
        /// 自定义规则地块
        /// </summary>
        CustomRuleTile = 2,
        /// <summary>
        /// 代码自动创建tile
        /// </summary>
        Sprite = 3,
    }

} 

