
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum UnitType
    {
        /// <summary>
        /// 玩家
        /// </summary>
        Player = 0,
        /// <summary>
        /// 无业游民
        /// </summary>
        HomeLess = 1,
        /// <summary>
        /// 农民
        /// </summary>
        Famer = 2,
        /// <summary>
        /// 樵夫
        /// </summary>
        LumberJack = 3,
        /// <summary>
        /// 渔夫
        /// </summary>
        FisherMan = 4,
        /// <summary>
        /// 矿工
        /// </summary>
        Miner = 5,
        /// <summary>
        /// 面包师
        /// </summary>
        Baker = 6,
        /// <summary>
        /// 厨师
        /// </summary>
        Cook = 7,
        /// <summary>
        /// 铁匠
        /// </summary>
        BlackSmith = 8,
        /// <summary>
        /// 木匠
        /// </summary>
        Carpenter = 9,
        /// <summary>
        /// 裁缝
        /// </summary>
        Tailor = 10,
        /// <summary>
        /// 陶工
        /// </summary>
        Potter = 11,
        /// <summary>
        /// 酿酒师
        /// </summary>
        Brewer = 12,
        /// <summary>
        /// 珠宝匠
        /// </summary>
        Jeweler = 13,
        /// <summary>
        /// 商人
        /// </summary>
        Merchant = 14,
        /// <summary>
        /// 医生
        /// </summary>
        Physician = 15,
        /// <summary>
        /// 教师
        /// </summary>
        Teacher = 16,
        /// <summary>
        /// 牧师
        /// </summary>
        Priest = 17,
        /// <summary>
        /// 士兵
        /// </summary>
        Soldier = 18,
        /// <summary>
        /// 车夫
        /// </summary>
        CartDriver = 19,
        /// <summary>
        /// 吟游诗人
        /// </summary>
        Bard = 20,
        /// <summary>
        /// 演员
        /// </summary>
        Actor = 21,
        /// <summary>
        /// 管理者
        /// </summary>
        Clerk = 22,
        /// <summary>
        /// 税务官
        /// </summary>
        TxCollector = 23,
        /// <summary>
        /// 学者
        /// </summary>
        Scholar = 24,
        /// <summary>
        /// 贵族
        /// </summary>
        Noble = 25,
        /// <summary>
        /// 工程师
        /// </summary>
        Engineer = 26,
        /// <summary>
        /// 冒险者
        /// </summary>
        Adventurer = 27,
        /// <summary>
        /// 小偷
        /// </summary>
        Chief = 28,
    }

} 

