
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum UnitType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 玩家
        /// </summary>
        Player = 1,
        /// <summary>
        /// 普通怪
        /// </summary>
        Monster = 2,
        /// <summary>
        /// 精英怪
        /// </summary>
        EliteMonster = 3,
        /// <summary>
        /// 小Boss
        /// </summary>
        LittleBoss = 4,
        /// <summary>
        /// 最终Boss
        /// </summary>
        FinalBoss = 5,
    }

} 

