
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class ActionConfigCategory : Singleton<ActionConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, ActionConfig> _dataMap;
        private readonly List<ActionConfig> _dataList;
        
        public ActionConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ActionConfig>();
            _dataList = new List<ActionConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                ActionConfig _v;
                _v = global::ET.ActionConfig.DeserializeActionConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, ActionConfig> GetAll() => _dataMap;
        public Dictionary<int, ActionConfig> DataMap => _dataMap;
        public List<ActionConfig> DataList => _dataList;

        public ActionConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public ActionConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

