
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ActionConfig : Luban.BeanBase
    {
        public ActionConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            ActionType = (ActionType)_buf.ReadInt();
            NumericType = (ENumericType)_buf.ReadInt();

            EndInit();
        }

        public static ActionConfig DeserializeActionConfig(ByteBuf _buf)
        {
            return new ActionConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 技能行为类型
        /// </summary>
        public readonly ActionType ActionType;
        /// <summary>
        /// 数值类型
        /// </summary>
        public readonly ENumericType NumericType;
    
        public const int __ID__ = 1209614648;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ActionType:" + ActionType + ","
            + "NumericType:" + NumericType + ","
            + "}";
        }

        partial void EndRef();
    }

}

