
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ParticleEffectConfig : Luban.BeanBase
    {
        public ParticleEffectConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            UnitConfigId = _buf.ReadInt();
            PrefabName = _buf.ReadString();
            TotalTime = _buf.ReadInt();
            IsFollowUnit = _buf.ReadBool();
            {int n0 = _buf.ReadSize(); InitPos = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); InitPos.Add(_e0);}}
            {int n0 = _buf.ReadSize(); InitScale = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); InitScale.Add(_e0);}}

            EndInit();
        }

        public static ParticleEffectConfig DeserializeParticleEffectConfig(ByteBuf _buf)
        {
            return new ParticleEffectConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 特效UnitConfigId
        /// </summary>
        public readonly int UnitConfigId;
        /// <summary>
        /// 特效资源名称
        /// </summary>
        public readonly string PrefabName;
        /// <summary>
        /// 存在总时长
        /// </summary>
        public readonly int TotalTime;
        /// <summary>
        /// 是否跟随
        /// </summary>
        public readonly bool IsFollowUnit;
        /// <summary>
        /// 初始位置
        /// </summary>
        public readonly System.Collections.Generic.List<float> InitPos;
        /// <summary>
        /// 初始缩放
        /// </summary>
        public readonly System.Collections.Generic.List<float> InitScale;
    
        public const int __ID__ = -447654407;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitConfigId:" + UnitConfigId + ","
            + "PrefabName:" + PrefabName + ","
            + "TotalTime:" + TotalTime + ","
            + "IsFollowUnit:" + IsFollowUnit + ","
            + "InitPos:" + Luban.StringUtil.CollectionToString(InitPos) + ","
            + "InitScale:" + Luban.StringUtil.CollectionToString(InitScale) + ","
            + "}";
        }

        partial void EndRef();
    }

}

