
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class RoleConfig : Luban.BeanBase
    {
        public RoleConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            RoleName = _buf.ReadString();
            Attack = _buf.ReadInt();
            Defense = _buf.ReadInt();
            Speed = _buf.ReadFloat();
            MaxHP = _buf.ReadInt();
            CriticalStrike = _buf.ReadInt();
            SkillHurt = _buf.ReadInt();
            ResPath = _buf.ReadString();

            EndInit();
        }

        public static RoleConfig DeserializeRoleConfig(ByteBuf _buf)
        {
            return new RoleConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 角色名称
        /// </summary>
        public readonly string RoleName;
        /// <summary>
        /// 攻击力
        /// </summary>
        public readonly int Attack;
        /// <summary>
        /// 防御值
        /// </summary>
        public readonly int Defense;
        /// <summary>
        /// 速度
        /// </summary>
        public readonly float Speed;
        /// <summary>
        /// 最大生命值
        /// </summary>
        public readonly int MaxHP;
        /// <summary>
        /// 暴击伤害
        /// </summary>
        public readonly int CriticalStrike;
        /// <summary>
        /// 技能伤害
        /// </summary>
        public readonly int SkillHurt;
        /// <summary>
        /// 角色资源路径
        /// </summary>
        public readonly string ResPath;
    
        public const int __ID__ = -1280631944;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "RoleName:" + RoleName + ","
            + "Attack:" + Attack + ","
            + "Defense:" + Defense + ","
            + "Speed:" + Speed + ","
            + "MaxHP:" + MaxHP + ","
            + "CriticalStrike:" + CriticalStrike + ","
            + "SkillHurt:" + SkillHurt + ","
            + "ResPath:" + ResPath + ","
            + "}";
        }

        partial void EndRef();
    }

}

