
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum DrawType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 单个
        /// </summary>
        Single = 1,
        /// <summary>
        /// 拖拽(当前规则：x，y不能大于1)
        /// </summary>
        Drag = 2,
    }

} 

