
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum DrawType
    {
        /// <summary>
        /// 单个
        /// </summary>
        Single = 0,
        /// <summary>
        /// 拖拽
        /// </summary>
        Drag = 1,
    }

} 

