
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum LandType
    {
        /// <summary>
        /// 地面
        /// </summary>
        Floor = 0,
        /// <summary>
        /// 建筑
        /// </summary>
        Build = 1,
        /// <summary>
        /// 道路
        /// </summary>
        Road = 2,
        /// <summary>
        /// 水
        /// </summary>
        Water = 3,
        /// <summary>
        /// 农田
        /// </summary>
        Farm = 4,
    }

} 

