
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class TileItemConfigCategory : Singleton<TileItemConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, TileItemConfig> _dataMap;
        private readonly List<TileItemConfig> _dataList;
        
        public TileItemConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TileItemConfig>();
            _dataList = new List<TileItemConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                TileItemConfig _v;
                _v = global::ET.TileItemConfig.DeserializeTileItemConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, TileItemConfig> GetAll() => _dataMap;
        public Dictionary<int, TileItemConfig> DataMap => _dataMap;
        public List<TileItemConfig> DataList => _dataList;

        public TileItemConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public TileItemConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

