
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class TileItemGroupConfigCategory : Singleton<TileItemGroupConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, TileItemGroupConfig> _dataMap;
        private readonly List<TileItemGroupConfig> _dataList;
        
        public TileItemGroupConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, TileItemGroupConfig>();
            _dataList = new List<TileItemGroupConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                TileItemGroupConfig _v;
                _v = global::ET.TileItemGroupConfig.DeserializeTileItemGroupConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, TileItemGroupConfig> GetAll() => _dataMap;
        public Dictionary<int, TileItemGroupConfig> DataMap => _dataMap;
        public List<TileItemGroupConfig> DataList => _dataList;

        public TileItemGroupConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public TileItemGroupConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

