
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class UnitConfig : Luban.BeanBase
    {
        public UnitConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            UnitType = (UnitType)_buf.ReadInt();
            Name = _buf.ReadString();
            Des = _buf.ReadString();
            {int n0 = _buf.ReadSize(); NumericTypeValue = new System.Collections.Generic.Dictionary<ENumericType, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { ENumericType _k0;  _k0 = (ENumericType)_buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     NumericTypeValue.Add(_k0, _v0);}}
            {int n0 = _buf.ReadSize(); InitCastConfigIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); InitCastConfigIds.Add(_e0);}}
            {int n0 = _buf.ReadSize(); InitScale = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); InitScale.Add(_e0);}}
            ResName = _buf.ReadString();

            EndInit();
        }

        public static UnitConfig DeserializeUnitConfig(ByteBuf _buf)
        {
            return new UnitConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly UnitType UnitType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Des;
        /// <summary>
        /// 数值
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<ENumericType, long> NumericTypeValue;
        /// <summary>
        /// 初始化技能数据
        /// </summary>
        public readonly System.Collections.Generic.List<int> InitCastConfigIds;
        /// <summary>
        /// 初始缩放
        /// </summary>
        public readonly System.Collections.Generic.List<float> InitScale;
        /// <summary>
        /// 资源名称
        /// </summary>
        public readonly string ResName;
    
        public const int __ID__ = -568528378;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitType:" + UnitType + ","
            + "Name:" + Name + ","
            + "Des:" + Des + ","
            + "NumericTypeValue:" + Luban.StringUtil.CollectionToString(NumericTypeValue) + ","
            + "InitCastConfigIds:" + Luban.StringUtil.CollectionToString(InitCastConfigIds) + ","
            + "InitScale:" + Luban.StringUtil.CollectionToString(InitScale) + ","
            + "ResName:" + ResName + ","
            + "}";
        }

        partial void EndRef();
    }

}

