
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class MonsterConfigCategory : Singleton<MonsterConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, MonsterConfig> _dataMap;
        private readonly List<MonsterConfig> _dataList;
        
        public MonsterConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MonsterConfig>();
            _dataList = new List<MonsterConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                MonsterConfig _v;
                _v = global::ET.MonsterConfig.DeserializeMonsterConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, MonsterConfig> GetAll() => _dataMap;
        public Dictionary<int, MonsterConfig> DataMap => _dataMap;
        public List<MonsterConfig> DataList => _dataList;

        public MonsterConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public MonsterConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

