
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class MonsterConfig : Luban.BeanBase
    {
        public MonsterConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            UnitType = (UnitType)_buf.ReadInt();
            Name = _buf.ReadString();
            Des = _buf.ReadString();
            Attack = _buf.ReadInt();
            Hp = _buf.ReadInt();
            CriticalHit = _buf.ReadInt();
            SkillHit = _buf.ReadInt();
            ResName = _buf.ReadString();

            EndInit();
        }

        public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
        {
            return new MonsterConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly UnitType UnitType;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Des;
        /// <summary>
        /// 基础攻击
        /// </summary>
        public readonly int Attack;
        /// <summary>
        /// 基础生命
        /// </summary>
        public readonly int Hp;
        /// <summary>
        /// 暴击伤害
        /// </summary>
        public readonly int CriticalHit;
        /// <summary>
        /// 技能伤害
        /// </summary>
        public readonly int SkillHit;
        /// <summary>
        /// 图片名称
        /// </summary>
        public readonly string ResName;
    
        public const int __ID__ = -55174244;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "UnitType:" + UnitType + ","
            + "Name:" + Name + ","
            + "Des:" + Des + ","
            + "Attack:" + Attack + ","
            + "Hp:" + Hp + ","
            + "CriticalHit:" + CriticalHit + ","
            + "SkillHit:" + SkillHit + ","
            + "ResName:" + ResName + ","
            + "}";
        }

        partial void EndRef();
    }

}

