
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class TileData : Luban.BeanBase
    {
        public TileData(ByteBuf _buf) 
        {
            ResName = _buf.ReadString();
            TileType = (TileType)_buf.ReadInt();
            DrawType = (DrawType)_buf.ReadInt();

            EndInit();
        }

        public static TileData DeserializeTileData(ByteBuf _buf)
        {
            return new TileData(_buf);
        }

        /// <summary>
        /// 资源名称
        /// </summary>
        public readonly string ResName;
        /// <summary>
        /// 资源类型
        /// </summary>
        public readonly TileType TileType;
        /// <summary>
        /// 绘制类型
        /// </summary>
        public readonly DrawType DrawType;
    
        public const int __ID__ = -2041834600;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "ResName:" + ResName + ","
            + "TileType:" + TileType + ","
            + "DrawType:" + DrawType + ","
            + "}";
        }

        partial void EndRef();
    }

}

