
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class TileItemGroupConfig : Luban.BeanBase
    {
        public TileItemGroupConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Desc = _buf.ReadString();

            EndInit();
        }

        public static TileItemGroupConfig DeserializeTileItemGroupConfig(ByteBuf _buf)
        {
            return new TileItemGroupConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
    
        public const int __ID__ = -277899040;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Desc:" + Desc + ","
            + "}";
        }

        partial void EndRef();
    }

}

