
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class TileItemConfig : Luban.BeanBase
    {
        public TileItemConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Title = _buf.ReadString();
            Desc = _buf.ReadString();
            {int n0 = _buf.ReadSize(); NumericTypeValue = new System.Collections.Generic.Dictionary<ENumericType, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { ENumericType _k0;  _k0 = (ENumericType)_buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     NumericTypeValue.Add(_k0, _v0);}}
            {int n0 = _buf.ReadSize(); CellData = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); CellData.Add(_e0);}}
            TileData = global::ET.TileData.DeserializeTileData(_buf);
            {int n0 = _buf.ReadSize(); PreviewPrefabData = new System.Collections.Generic.Dictionary<string, TileType>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { string _k0;  _k0 = _buf.ReadString(); TileType _v0;  _v0 = (TileType)_buf.ReadInt();     PreviewPrefabData.Add(_k0, _v0);}}
            UIName = _buf.ReadString();
            GroupID = _buf.ReadInt();

            EndInit();
        }

        public static TileItemConfig DeserializeTileItemConfig(ByteBuf _buf)
        {
            return new TileItemConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 标题
        /// </summary>
        public readonly string Title;
        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;
        /// <summary>
        /// 数值
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<ENumericType, long> NumericTypeValue;
        /// <summary>
        /// 地格数据(宽、高)
        /// </summary>
        public readonly System.Collections.Generic.List<int> CellData;
        /// <summary>
        /// 地格数据
        /// </summary>
        public readonly TileData TileData;
        /// <summary>
        /// 预览资源名称
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<string, TileType> PreviewPrefabData;
        /// <summary>
        /// UI资源名称
        /// </summary>
        public readonly string UIName;
        /// <summary>
        /// 组ID
        /// </summary>
        public readonly int GroupID;
    
        public const int __ID__ = -1071248989;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            TileData?.ResolveRef();
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Title:" + Title + ","
            + "Desc:" + Desc + ","
            + "NumericTypeValue:" + Luban.StringUtil.CollectionToString(NumericTypeValue) + ","
            + "CellData:" + Luban.StringUtil.CollectionToString(CellData) + ","
            + "TileData:" + TileData + ","
            + "PreviewPrefabData:" + Luban.StringUtil.CollectionToString(PreviewPrefabData) + ","
            + "UIName:" + UIName + ","
            + "GroupID:" + GroupID + ","
            + "}";
        }

        partial void EndRef();
    }

}

