
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    public partial struct CreateMonsterData
    {
        public CreateMonsterData(ByteBuf _buf) 
        {
            MonsterConfigId = _buf.ReadInt();
            Interval = _buf.ReadFloat();
            CreateNum = _buf.ReadInt();

            PostInit();
        }

        public static CreateMonsterData DeserializeCreateMonsterData(ByteBuf _buf)
        {
            return new CreateMonsterData(_buf);
        }

        public readonly int MonsterConfigId;
        public readonly float Interval;
        public readonly int CreateNum;
    

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "MonsterConfigId:" + MonsterConfigId + ","
            + "Interval:" + Interval + ","
            + "CreateNum:" + CreateNum + ","
            + "}";
        }

        partial void PostInit();
        partial void EndRef();
    }

}

