
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class GameLevelConfigCategory : Singleton<GameLevelConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, GameLevelConfig> _dataMap;
        private readonly List<GameLevelConfig> _dataList;
        
        public GameLevelConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, GameLevelConfig>();
            _dataList = new List<GameLevelConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                GameLevelConfig _v;
                _v = global::ET.GameLevelConfig.DeserializeGameLevelConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, GameLevelConfig> GetAll() => _dataMap;
        public Dictionary<int, GameLevelConfig> DataMap => _dataMap;
        public List<GameLevelConfig> DataList => _dataList;

        public GameLevelConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public GameLevelConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

