
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum ActionType
    {
        /// <summary>
        /// 改变目标数值，如果是buff，删除会还原数值
        /// </summary>
        NumericChange = 0,
        /// <summary>
        /// 造成伤害
        /// </summary>
        Damage = 1,
        /// <summary>
        /// 创建子弹
        /// </summary>
        CastBullet = 2,
    }

} 

