
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum ActionType
    {
        /// <summary>
        /// 改变目标数值，如果是buff，删除会还原数值
        /// </summary>
        NumericChange = 0,
        /// <summary>
        /// 造成伤害
        /// </summary>
        Damage = 1,
        /// <summary>
        /// 创建技能
        /// </summary>
        CreateCast = 2,
        /// <summary>
        /// 创建Buff
        /// </summary>
        CastBuff = 3,
        /// <summary>
        /// 创建特效
        /// </summary>
        CastParticle = 4,
        /// <summary>
        /// 移动方向直线移动
        /// </summary>
        DirLineMove = 5,
        /// <summary>
        /// 正前方直线移动
        /// </summary>
        ForwardLineMove = 6,
        /// <summary>
        /// 曲线移动
        /// </summary>
        CurveMove = 7,
        /// <summary>
        /// 随机位置
        /// </summary>
        RandomPos = 8,
        /// <summary>
        /// 随机方向直线移动
        /// </summary>
        RandomDirLineMove = 9,
        /// <summary>
        /// 碰撞销毁自身
        /// </summary>
        HitDestroySelf = 10,
        /// <summary>
        /// 向上抛物线
        /// </summary>
        UpParabola = 11,
        /// <summary>
        /// 碰撞转向
        /// </summary>
        HitRotate = 12,
        /// <summary>
        /// 技能持续时间结束，自动销毁
        /// </summary>
        AutoDispose = 13,
    }

} 

