
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class BuffConfig : Luban.BeanBase
    {
        public BuffConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            TotalTime = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); AddAction = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AddAction.Add(_e0);}}
            {int n0 = _buf.ReadSize(); AddActionParam = new System.Collections.Generic.List<long>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { long _e0;  _e0 = _buf.ReadLong(); AddActionParam.Add(_e0);}}
            TickTime = _buf.ReadFloat();
            {int n0 = _buf.ReadSize(); TickAction = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TickAction.Add(_e0);}}
            {int n0 = _buf.ReadSize(); TickActionParam = new System.Collections.Generic.List<long>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { long _e0;  _e0 = _buf.ReadLong(); TickActionParam.Add(_e0);}}
            {int n0 = _buf.ReadSize(); RemoveAction = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RemoveAction.Add(_e0);}}
            {int n0 = _buf.ReadSize(); RemoveActionParam = new System.Collections.Generic.List<long>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { long _e0;  _e0 = _buf.ReadLong(); RemoveActionParam.Add(_e0);}}

            EndInit();
        }

        public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
        {
            return new BuffConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 总时长
        /// </summary>
        public readonly int TotalTime;
        /// <summary>
        /// 效果
        /// </summary>
        public readonly System.Collections.Generic.List<int> AddAction;
        /// <summary>
        /// 效果参数
        /// </summary>
        public readonly System.Collections.Generic.List<long> AddActionParam;
        /// <summary>
        /// Tick间隔时间
        /// </summary>
        public readonly float TickTime;
        /// <summary>
        /// 效果
        /// </summary>
        public readonly System.Collections.Generic.List<int> TickAction;
        /// <summary>
        /// 效果参数
        /// </summary>
        public readonly System.Collections.Generic.List<long> TickActionParam;
        /// <summary>
        /// 效果
        /// </summary>
        public readonly System.Collections.Generic.List<int> RemoveAction;
        /// <summary>
        /// 效果参数
        /// </summary>
        public readonly System.Collections.Generic.List<long> RemoveActionParam;
    
        public const int __ID__ = -1370631787;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TotalTime:" + TotalTime + ","
            + "AddAction:" + Luban.StringUtil.CollectionToString(AddAction) + ","
            + "AddActionParam:" + Luban.StringUtil.CollectionToString(AddActionParam) + ","
            + "TickTime:" + TickTime + ","
            + "TickAction:" + Luban.StringUtil.CollectionToString(TickAction) + ","
            + "TickActionParam:" + Luban.StringUtil.CollectionToString(TickActionParam) + ","
            + "RemoveAction:" + Luban.StringUtil.CollectionToString(RemoveAction) + ","
            + "RemoveActionParam:" + Luban.StringUtil.CollectionToString(RemoveActionParam) + ","
            + "}";
        }

        partial void EndRef();
    }

}

