
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class BulletConfigCategory : Singleton<BulletConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, BulletConfig> _dataMap;
        private readonly List<BulletConfig> _dataList;
        
        public BulletConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BulletConfig>();
            _dataList = new List<BulletConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                BulletConfig _v;
                _v = global::ET.BulletConfig.DeserializeBulletConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, BulletConfig> GetAll() => _dataMap;
        public Dictionary<int, BulletConfig> DataMap => _dataMap;
        public List<BulletConfig> DataList => _dataList;

        public BulletConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public BulletConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

