
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum CastType
    {
        /// <summary>
        /// 主动技能
        /// </summary>
        ActiveCast = 0,
        /// <summary>
        /// 被动技能
        /// </summary>
        PassiveCast = 1,
        /// <summary>
        /// 一次性技能，针对当前某个技能进行数据调整
        /// </summary>
        OnceCast = 2,
    }

} 

