
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum SelectType
    {
        /// <summary>
        /// 范围内距离最近的一个
        /// </summary>
        OneWithInRange = 0,
        /// <summary>
        /// 圆形区域内所有
        /// </summary>
        Circular = 1,
        /// <summary>
        /// 扇形区域内所有
        /// </summary>
        Sector = 2,
    }

} 

