
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum ENumericType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 金钱_0 (Int)
        /// </summary>
        Money0 = 100000,
        /// <summary>
        /// 钻石_0 (Int)
        /// </summary>
        Diamond0 = 100001,
        /// <summary>
        /// 声望值_0 (Int)
        /// </summary>
        Prestige0 = 100002,
        /// <summary>
        /// 人口上限_0 (Int)
        /// </summary>
        PopulationLimit0 = 100003,
        /// <summary>
        /// 心情值_0 (Int)
        /// </summary>
        Feeling0 = 200000,
        /// <summary>
        /// 薪资值_0 (Int)
        /// </summary>
        Salary0 = 200001,
        /// <summary>
        /// 薪资速率_0 (Long)
        /// </summary>
        SalartRate0 = 200002,
        /// <summary>
        /// 饥饿值_0 (Int)
        /// </summary>
        Hunger0 = 200003,
        /// <summary>
        /// 饥饿速率_0 (Long)
        /// </summary>
        HungerRate0 = 200004,
        /// <summary>
        /// 饱腹值_0 (Int)
        /// </summary>
        Satiety0 = 200005,
        /// <summary>
        /// 健康值_0 (Int)
        /// </summary>
        Health0 = 200006,
        /// <summary>
        /// 产出值_0 (Int)
        /// </summary>
        OutPut0 = 200007,
        /// <summary>
        /// 产出速率_0 (Long)
        /// </summary>
        OutPutRate0 = 200008,
        /// <summary>
        /// 幸福值_0 (Int)
        /// </summary>
        Happiness0 = 200009,
        /// <summary>
        /// 招募值_0 (Int)
        /// </summary>
        Recruit0 = 200010,
        /// <summary>
        /// 价格_0 (Int)
        /// </summary>
        Price0 = 200011,
    }

} 

