
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class ChapterConfigCategory : Singleton<ChapterConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, ChapterConfig> _dataMap;
        private readonly List<ChapterConfig> _dataList;
        
        public ChapterConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ChapterConfig>();
            _dataList = new List<ChapterConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                ChapterConfig _v;
                _v = global::ET.ChapterConfig.DeserializeChapterConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, ChapterConfig> GetAll() => _dataMap;
        public Dictionary<int, ChapterConfig> DataMap => _dataMap;
        public List<ChapterConfig> DataList => _dataList;

        public ChapterConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public ChapterConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

