
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ChapterConfig : Luban.BeanBase
    {
        public ChapterConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); GameLevels = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); GameLevels.Add(_e0);}}
            {int n0 = _buf.ReadSize(); CrossChapterAward = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); CrossChapterAward.Add(_e0);}}

            EndInit();
        }

        public static ChapterConfig DeserializeChapterConfig(ByteBuf _buf)
        {
            return new ChapterConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 关卡
        /// </summary>
        public readonly System.Collections.Generic.List<int> GameLevels;
        /// <summary>
        /// 通关奖励
        /// </summary>
        public readonly System.Collections.Generic.List<int> CrossChapterAward;
    
        public const int __ID__ = 155381199;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "GameLevels:" + Luban.StringUtil.CollectionToString(GameLevels) + ","
            + "CrossChapterAward:" + Luban.StringUtil.CollectionToString(CrossChapterAward) + ","
            + "}";
        }

        partial void EndRef();
    }

}

