
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class EnergyBlockConfig : Luban.BeanBase
    {
        public EnergyBlockConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            {int n0 = _buf.ReadSize(); NumericDataType = new System.Collections.Generic.Dictionary<ENumericType, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { ENumericType _k0;  _k0 = (ENumericType)_buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     NumericDataType.Add(_k0, _v0);}}
            ResName = _buf.ReadString();

            EndInit();
        }

        public static EnergyBlockConfig DeserializeEnergyBlockConfig(ByteBuf _buf)
        {
            return new EnergyBlockConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 数值
        /// </summary>
        public readonly System.Collections.Generic.Dictionary<ENumericType, long> NumericDataType;
        /// <summary>
        /// 资源名称
        /// </summary>
        public readonly string ResName;
    
        public const int __ID__ = -922016153;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "NumericDataType:" + Luban.StringUtil.CollectionToString(NumericDataType) + ","
            + "ResName:" + ResName + ","
            + "}";
        }

        partial void EndRef();
    }

}

