
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class EnergyBlockConfigCategory : Singleton<EnergyBlockConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, EnergyBlockConfig> _dataMap;
        private readonly List<EnergyBlockConfig> _dataList;
        
        public EnergyBlockConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, EnergyBlockConfig>();
            _dataList = new List<EnergyBlockConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                EnergyBlockConfig _v;
                _v = global::ET.EnergyBlockConfig.DeserializeEnergyBlockConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, EnergyBlockConfig> GetAll() => _dataMap;
        public Dictionary<int, EnergyBlockConfig> DataMap => _dataMap;
        public List<EnergyBlockConfig> DataList => _dataList;

        public EnergyBlockConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public EnergyBlockConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

