
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class GameLevelConfig : Luban.BeanBase
    {
        public GameLevelConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            LevelTitle = _buf.ReadString();
            LevelDes = _buf.ReadString();
            ResName = _buf.ReadString();
            {int n0 = _buf.ReadSize(); CrossGameLevelAwards = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); CrossGameLevelAwards.Add(_e0);}}
            MapResName = _buf.ReadString();

            EndInit();
        }

        public static GameLevelConfig DeserializeGameLevelConfig(ByteBuf _buf)
        {
            return new GameLevelConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 关卡标题
        /// </summary>
        public readonly string LevelTitle;
        /// <summary>
        /// 关卡描述
        /// </summary>
        public readonly string LevelDes;
        /// <summary>
        /// 资源名称
        /// </summary>
        public readonly string ResName;
        /// <summary>
        /// 通过关卡奖励
        /// </summary>
        public readonly System.Collections.Generic.List<int> CrossGameLevelAwards;
        /// <summary>
        /// 地图资源
        /// </summary>
        public readonly string MapResName;
    
        public const int __ID__ = -909516684;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "LevelTitle:" + LevelTitle + ","
            + "LevelDes:" + LevelDes + ","
            + "ResName:" + ResName + ","
            + "CrossGameLevelAwards:" + Luban.StringUtil.CollectionToString(CrossGameLevelAwards) + ","
            + "MapResName:" + MapResName + ","
            + "}";
        }

        partial void EndRef();
    }

}

