
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{ 
    public enum UnitType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 玩家
        /// </summary>
        Player = 1,
        /// <summary>
        /// 普通
        /// </summary>
        Monster = 2,
        /// <summary>
        /// 精英
        /// </summary>
        EliteMonster = 3,
        /// <summary>
        /// 统领
        /// </summary>
        LittleBoss = 4,
        /// <summary>
        /// 首领
        /// </summary>
        FinalBoss = 5,
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 6,
        /// <summary>
        /// 特效
        /// </summary>
        ParticleEffect = 7,
        /// <summary>
        /// 技能
        /// </summary>
        Cast = 8,
        /// <summary>
        /// 摄像机
        /// </summary>
        Camera = 9,
        /// <summary>
        /// 能量块
        /// </summary>
        EnergyBlock = 10,
    }

} 

