
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class RoleConfigCategory : Singleton<RoleConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, RoleConfig> _dataMap;
        private readonly List<RoleConfig> _dataList;
        
        public RoleConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, RoleConfig>();
            _dataList = new List<RoleConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                RoleConfig _v;
                _v = global::ET.RoleConfig.DeserializeRoleConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, RoleConfig> GetAll() => _dataMap;
        public Dictionary<int, RoleConfig> DataMap => _dataMap;
        public List<RoleConfig> DataList => _dataList;

        public RoleConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public RoleConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

